config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root "students#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    has_many:students
    validates_presence_of :title, :url
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :project
  validates_presence_of :name, :url , :project_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
#controllers for project entities
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :url)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :url, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= project.url %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= student.url %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= student.project_id %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>